FechamentoSeal/Seal/Controllers/NotaFiscalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Seal.Controllers
{
    public class NotaFiscalController : HController
    {
        // GET: NotaFiscal
        public ActionResult Index()
        {
            if (!Logado())
                return RedirectToAction("Index", "Home");

            CheckUser();

            //Cria conexão
            DAO.NfeDAO DAO = new DAO.NfeDAO();
            //Traz documentos
            List<Assecontweb.Extend.Nfe.Danfe.NotaFiscal> danfes = new List<Assecontweb.Extend.Nfe.Danfe.NotaFiscal>();
            string erro = "";
            if(DAO.GetDanfes(ref danfes, ref erro))
            {
                //Cria modelo p/ View
                Models.NotaFiscal.IndexModel model = new Models.NotaFiscal.IndexModel();
                //Atribui documentos no modelo
                model.title = "Notas Fiscais Importadas";

                model.danfes = danfes;
                return View(model);
            }
            else
            {
                Models.SealException ex = new Models.SealException(this, new Exception(erro));
                ex.SendEmail();
                return RedirectToAction("Index", "Home");
            }
        }
    }
}

FechamentoSeal/Seal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Seal</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @*@Scripts.Render("~/bundles/dropzonescripts")*@
    @*@Styles.Render("~/Content/dropzonescss")*@
    <script src="~/Scripts/dropzone/dropzone.js" type="text/javascript"></script>
    <link href="~/Content/dropzone/basic.css" rel="stylesheet" />
    <link href="~/Content/dropzone/dropzone.css" rel="stylesheet" />
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Seal", "Inicio", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-left">
                    <li>@Html.ActionLink("Notas", "Index", "NotaFiscal")</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (ViewBag.Interno)
                    {
                        <li><a href="~/Upload/Index/">Upload</a>@*@Html.ActionLink("Upload", "Index", "Cliente")*@</li>
                    }
                    else
                    {
                        if (ViewBag.btnUpload == null || ViewBag.btnUpload)
                        {
                            <li><a href="~/Cliente/Index/">Upload</a>@*@Html.ActionLink("Upload", "Index", "Cliente")*@</li>
                        }
                    }
                    <li>@Html.ActionLink("Sair", "Sair", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Seal Fechamento</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

FechamentoSeal/Seal/Views/Shared/_Layout.old.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>